### ISSUE TITLE
Get issue with twrp zip file flashing losses modem after 1st reboot

### ISSUE THREAD

**Issue by cobrax05** [corsicanu/9810-bootloaders_and_modems#2]

**Comment by corsicanu** [comment]
Can you try to reflash the release with older twrp like 3.4?

**Comment by ossage** [comment]
Happened the same? Originally flashed using twrp-3.5.2_9-0.
IMEI: Unknown. Handset says it is a n975 instead of n960f (Noble 1.3)
Odin reflash not worked, twrp 3.4.0-0 reflash not worked.
What next? Try to restore EFS?

**Comment by corsicanu** [comment]
Don't touch efs, just try redownload and reflash via latest twrp. Handset model change is because of the rom, it has nothing to do with this repo and/or the files shared here.

**Comment by ossage** [comment]
Using latest TWRP, the reflash of latest release did not work. Went back to N960FXXS7FUA1 (jan.11), no success.
Attached a logcat.
Next ideas: restore complete TWRP backup or restore a stock fw (with pain)?

**Comment by corsicanu** [comment]
FUA1 was never meant to work for you now since it's rev 7. 
Try older but same rev 8, as FUB1, FUC4 or FUD1 and see if anything changes.

**Comment by ossage** [comment]
Checked them all, did not help. What's going on? 
I've heard another guy facing this, but reported odin reflash to solve this issue.
What circumstances should be taken into account? 
I've been previously on twrp 3.4.0, RR 8.6.3,                FXXS6ETH4. 
Upgraded to                    twrp 3.5.2, Noble 1.3 and the FXXU8FUE1 pack. Does it matter?
