### ISSUE TITLE
No imei

### ISSUE THREAD

**Issue by pitelasssss** [corsicanu/9810-bootloaders_and_modems#3]
Hello sir
i have a   Note9 N960F   im on   noble 1.5 rom  and last night  ive flashed  your  last  n960f  twrp flashable
now i cant do nothig, i dont have imei , baseband... and im not able to flash stock firw   says   sw rev check fail bootloader device 9 binary 8

need help

**Comment by ananjaser1211** [comment]
for flashing stock Download a U9/S9 stock firmware. you are trying to flash an U8/S8 firmware. 

regarding IMEI, something is wrong with the flashable after few firmware updates, flashing CP and BL alone via odin should fix it.

**Comment by pitelasssss** [comment]
im flashing last firmw   for  N960F    TPH
![Sem Título](https://user-images.githubusercontent.com/5264243/130291902-39a4f4e3-ede0-4d48-97e3-331fb9a2c06c.png)
Ive tried  to flash  stock  bl  and   cp  from odin and got  failed

**Comment by ananjaser1211** [comment]
you are flashing S8 , your device has rev 9. odin wont let you flash an older revision. you must flash rev 9 such as https://samfw.com/firmware/SM-N960F/DBT/N960FXXS9FUH1

region does not matter, your TPH region does not currently have rev 8 firmware, you can flash DBT (germany) which has rev 9

**Comment by pitelasssss** [comment]
1st time i had issues  with this  bl/cp  zips
i heard on noble rom group that more users reported  no imei  and bugs like me

**Comment by ananjaser1211** [comment]
The flashable format is broken, if you want to update bl/cp in the future use the odin option, unless this repo is updated

**Comment by pitelasssss** [comment]
ok thanks for that info! i will try to flash  DBT  firmware   and see if  imei  comes back

**Comment by pitelasssss** [comment]
its ok now with  dbt fw  fully flashed
thanks again

**Comment by ananjaser1211** [comment]
welcome, glad it is fixed
